#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

mkdir -p docs docs/generated

no_mangle_count=$(rg -n '#\[no_mangle\]' rust/mtproxy-ffi/src | wc -l | tr -d ' ')
extern_c_count=$(rg -n 'extern\s*"C"' rust/mtproxy-ffi/src | wc -l | tr -d ' ')
unsafe_count=$(rg -n 'unsafe\s*\{' rust/mtproxy-ffi/src | wc -l | tr -d ' ')

rg -n '#\[no_mangle\]' rust/mtproxy-ffi/src > docs/generated/no_mangle_inventory.txt
rg -n 'extern\s*"C"' rust/mtproxy-ffi/src > docs/generated/extern_c_inventory.txt
rg -n 'unsafe\s*\{' rust/mtproxy-ffi/src > docs/generated/unsafe_inventory.txt

{
  echo 'kind,symbol,file,line,subsystem,risk,c_header'

  rg -n '^\s*pub\s+unsafe\s+extern\s+"C"\s+fn\s+([A-Za-z0-9_]+)|^\s*pub\s+extern\s+"C"\s+fn\s+([A-Za-z0-9_]+)' rust/mtproxy-ffi/src \
    | sed -E 's#^([^:]+):([0-9]+):.*fn ([A-Za-z0-9_]+).*#\1,\2,\3#' \
    | while IFS=',' read -r file line symbol; do
        subsystem="misc"
        risk="R1"
        header="rust/mtproxy-ffi/include/mtproxy_ffi.h"
        case "$symbol" in
          mtproxy_ffi_net_*|mtproxy_ffi_tcp_* ) subsystem="net"; risk="R3" ;;
          mtproxy_ffi_engine_* ) subsystem="engine"; risk="R2" ;;
          mtproxy_ffi_mtproto_* ) subsystem="mtproto"; risk="R3" ;;
          mtproxy_ffi_jobs_*|jobs_* ) subsystem="jobs"; risk="R2" ;;
          mtproxy_ffi_crypto_*|mtproxy_ffi_crc* ) subsystem="crypto"; risk="R3" ;;
          mtproxy_ffi_cfg_*|mtproxy_ffi_tl_*|mtproxy_ffi_sb_*|mtproxy_ffi_parse_* ) subsystem="common"; risk="R2" ;;
          rust_* ) subsystem="common"; risk="R1" ;;
        esac
        printf 'rust_export,%s,%s,%s,%s,%s,%s\n' "$symbol" "$file" "$line" "$subsystem" "$risk" "$header"
      done

  rg -n '^[[:space:]]*[A-Za-z_][A-Za-z0-9_[:space:]\*]*\s+(mtproxy_ffi_[A-Za-z0-9_]+|rust_[A-Za-z0-9_]+)\s*\(' rust/mtproxy-ffi/include/mtproxy_ffi.h \
    | sed -E 's#^([^:]+):([0-9]+):.*\s(mtproxy_ffi_[A-Za-z0-9_]+|rust_[A-Za-z0-9_]+)\s*\(.*#\1,\2,\3#' \
    | while IFS=',' read -r file line symbol; do
        subsystem="misc"
        risk="R1"
        case "$symbol" in
          mtproxy_ffi_net_*|mtproxy_ffi_tcp_* ) subsystem="net"; risk="R3" ;;
          mtproxy_ffi_engine_* ) subsystem="engine"; risk="R2" ;;
          mtproxy_ffi_mtproto_* ) subsystem="mtproto"; risk="R3" ;;
          mtproxy_ffi_jobs_*|jobs_* ) subsystem="jobs"; risk="R2" ;;
          mtproxy_ffi_crypto_*|mtproxy_ffi_crc* ) subsystem="crypto"; risk="R3" ;;
          mtproxy_ffi_cfg_*|mtproxy_ffi_tl_*|mtproxy_ffi_sb_*|mtproxy_ffi_parse_* ) subsystem="common"; risk="R2" ;;
          rust_* ) subsystem="common"; risk="R1" ;;
        esac
        printf 'c_header_decl,%s,%s,%s,%s,%s,%s\n' "$symbol" "$file" "$line" "$subsystem" "$risk" "$file"
      done
} > docs/ffi_symbol_index.csv

cat > docs/refactor_manifest.md <<MANIFEST
# Refactor Manifest (Dual-Runtime Transitional)

Generated by:
- scripts/generate_refactor_manifest.sh

## Inventory Summary
- Rust FFI exports (#[no_mangle]): ${no_mangle_count}
- Rust extern \"C\" declarations/defs: ${extern_c_count}
- Rust unsafe blocks in mtproxy-ffi: ${unsafe_count}

Detailed inventories:
- docs/generated/no_mangle_inventory.txt
- docs/generated/extern_c_inventory.txt
- docs/generated/unsafe_inventory.txt
- docs/ffi_symbol_index.csv

## Rules Enforced
- No new C ABI exports in transitional period.
- New runtime behavior lands in mtproxy-core or mtproxy-bin only.
- mtproxy-ffi is adapter-only while dual-runtime support remains.

## Migration Wave Order
1. Network core (net/*, tcp-rpc client/server/common) [R3]
2. Bootstrap/util (common/*, engine/*) [R2]
3. Crypto residuals and protocol helpers [R3]

## Risk Labels
- R0: pure wrapper glue
- R1: stateful local logic
- R2: cross-thread/global mutable state
- R3: protocol/security-critical paths
MANIFEST

{
  echo '# C-to-Rust Dependency Graph (Current Transitional State)'
  echo
  echo 'Generated from C callsites referencing `mtproxy_ffi_*` and `rust_*` symbols.'
  echo
  echo '## Edge Legend'
  echo '- `C module -> FFI symbol group -> Rust runtime area`'
  echo

  for dir in common crypto engine jobs mtproto net; do
    echo "## ${dir}"
    rg -n 'mtproxy_ffi_|rust_' "$dir" -g '!*.h' \
      | sed -E 's#^[^:]+:[0-9]+:.*(mtproxy_ffi_[A-Za-z0-9_]+|rust_[A-Za-z0-9_]+).*#\1#' \
      | sort -u \
      | awk '
          BEGIN { }
          {
            sym=$0;
            area="runtime/misc";
            if (sym ~ /^mtproxy_ffi_net_|^mtproxy_ffi_tcp_/) area="runtime/net";
            else if (sym ~ /^mtproxy_ffi_engine_/) area="runtime/engine";
            else if (sym ~ /^mtproxy_ffi_mtproto_/) area="runtime/mtproto";
            else if (sym ~ /^mtproxy_ffi_jobs_|^jobs_/) area="runtime/jobs";
            else if (sym ~ /^mtproxy_ffi_crypto_|^mtproxy_ffi_crc/) area="runtime/crypto";
            else if (sym ~ /^mtproxy_ffi_cfg_|^mtproxy_ffi_tl_|^mtproxy_ffi_sb_|^mtproxy_ffi_parse_|^rust_/) area="runtime/bootstrap+config";
            print "- " sym " -> " area;
          }'
    echo
  done
} > docs/c_to_rust_dependency_graph.md
