#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_FILE="${1:-${ROOT_DIR}/rust/mtproxy-bin/STEP15_REMAINING_C_UNITS.txt}"
TMP_FILE="$(mktemp)"

cleanup() {
  rm -f "${TMP_FILE}"
}
trap cleanup EXIT

make -pn -C "${ROOT_DIR}" \
  | awk '
      ($1 == "RUST_OBJECTS" || $1 == "LIB_OBJS_NORMAL") && $2 ~ /^[:+?]?=$/ {
        for (i = 3; i <= NF; i++) {
          print $i;
        }
      }
    ' \
  | tr ' ' '\n' \
  | sed '/^$/d' \
  | sed 's#^\${OBJ}/##; s#^objs/##' \
  | sed 's#\.rust\.o$#.c#; s#\.o$#.c#' \
  | sort -u > "${TMP_FILE}"

while IFS= read -r translation_unit; do
  if [ ! -f "${ROOT_DIR}/${translation_unit}" ]; then
    echo "missing source file in Step 15 runtime inventory: ${translation_unit}" >&2
    exit 1
  fi
done < "${TMP_FILE}"

entry_count="$(wc -l < "${TMP_FILE}")"

{
  echo "# Step 15 Remaining C Runtime Translation Units"
  echo "# Generated by scripts/step15_inventory.sh"
  echo "# Count: ${entry_count}"
  echo
  cat "${TMP_FILE}"
} > "${OUT_FILE}"

echo "wrote ${entry_count} Step 15 runtime translation units to ${OUT_FILE}"
